#!/usr/bin/env bash
# /root/build_recipe_sitemap.sh
#
# todo/20 chunks B + F — generates per-recipe sitemap.xml from
# `GET /recipes/sitemap` and atomically replaces the file inside
# the `recipe_list_web` nginx container.
#
# Chunk F form: <loc> uses the canonical English locale-prefixed path
# `/en/recipes/<id>`; each <url> carries 10 <xhtml:link rel="alternate"
# hreflang="<lang>"> entries plus an x-default. The locale-prefix
# router (chunk D) and the bot pre-renderer (chunk E) both consume
# these URLs end-to-end, so the hreflang ring is fully closed:
# Googlebot at /en/... discovers /ru/..., crawls /ru/... and
# verifies the return-link points back at /en/...
#
# Run by /etc/cron.d/recipes-sitemap at 06:00 UTC daily, 30 minutes
# after the recipes-backfill cron at 05:30.
#
# Logging: appends to /var/log/recipes_sitemap.log with ISO timestamp.
# Exit non-zero on any step so cron MAILTO surfaces failures.

set -euo pipefail

API_HOST="${RECIPES_API_HOST:-http://172.25.0.41:4000}"
PUBLIC_HOST="${RECIPES_PUBLIC_HOST:-https://recipies.mahallem.ist}"
CONTAINER="${RECIPES_WEB_CONTAINER:-recipe_list_web}"
NGINX_PATH="${RECIPES_NGINX_PATH:-/usr/share/nginx/html/sitemap.xml}"
LOG_FILE="${RECIPES_SITEMAP_LOG:-/var/log/recipes_sitemap.log}"

stamp() { date -u +"%Y-%m-%dT%H:%M:%SZ"; }
log()   { printf '[%s] %s\n' "$(stamp)" "$*" | tee -a "$LOG_FILE"; }

trap 'log "ERROR exit=$?"' ERR

TMP_JSON="$(mktemp)"
TMP_XML="$(mktemp)"
trap 'rm -f "$TMP_JSON" "$TMP_XML"' EXIT

log "fetching $API_HOST/recipes/sitemap"
curl -fsS --max-time 20 "$API_HOST/recipes/sitemap" >"$TMP_JSON"

COUNT="$(jq 'length' "$TMP_JSON")"
if ! [[ "$COUNT" =~ ^[0-9]+$ ]] || [ "$COUNT" -lt 1 ]; then
  log "refusing to publish empty/invalid sitemap (count=$COUNT)"
  exit 2
fi

log "rendering sitemap with $COUNT recipe URLs"
{
  printf '%s\n' '<?xml version="1.0" encoding="UTF-8"?>'
  printf '%s\n' '<!-- generated by build_recipe_sitemap.sh — do not edit by hand -->'
  printf '%s\n' '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"'
  printf '%s\n' '        xmlns:xhtml="http://www.w3.org/1999/xhtml">'

  printf '  <url>\n'
  printf '    <loc>%s/</loc>\n' "$PUBLIC_HOST"
  printf '    <changefreq>daily</changefreq>\n'
  printf '    <priority>1.0</priority>\n'
  printf '  </url>\n'
  printf '  <url>\n'
  printf '    <loc>%s/recipes</loc>\n' "$PUBLIC_HOST"
  printf '    <changefreq>daily</changefreq>\n'
  printf '    <priority>0.9</priority>\n'
  printf '  </url>\n'

  # Per-recipe URLs with the full hreflang ring. Canonical → /en/…,
  # ten <xhtml:link rel="alternate" hreflang="…"> entries (one per
  # supported locale, alphabetical), plus an x-default that aliases
  # the English copy. Locale list mirrors
  # recipe_list/lib/router/routes.dart and prerender/lib/render-utils.js.
  jq -r --arg base "$PUBLIC_HOST" '
    def hreflang_block($id):
      ["ar","de","en","es","fa","fr","it","ku","ru","tr"] |
      map("    <xhtml:link rel=\"alternate\" hreflang=\"\(.)\" href=\"\($base)/\(.)/recipes/\($id)\"/>") |
      join("\n");
    .[] |
    "  <url>\n" +
    "    <loc>\($base)/en/recipes/\(.id)</loc>\n" +
    "    <lastmod>\(.updatedAt)</lastmod>\n" +
    "    <changefreq>weekly</changefreq>\n" +
    "    <priority>0.8</priority>\n" +
    hreflang_block(.id) + "\n" +
    "    <xhtml:link rel=\"alternate\" hreflang=\"x-default\" href=\"\($base)/en/recipes/\(.id)\"/>\n" +
    "  </url>"
  ' "$TMP_JSON"

  printf '%s\n' '</urlset>'
} >"$TMP_XML"

# Validate XML before publishing.
if command -v xmllint >/dev/null 2>&1; then
  xmllint --noout "$TMP_XML"
fi

log "publishing to $CONTAINER:$NGINX_PATH"
docker cp "$TMP_XML" "$CONTAINER:$NGINX_PATH"
docker exec "$CONTAINER" chown 0:0 "$NGINX_PATH" || true
docker exec "$CONTAINER" chmod 0644 "$NGINX_PATH" || true

log "done count=$COUNT bytes=$(wc -c <"$TMP_XML" | tr -d ' ')"
