#!/usr/bin/env bash
# /root/build_recipe_sitemap.sh
#
# todo/20 chunk B — generates per-recipe sitemap.xml from
# `GET /recipes/sitemap` and atomically replaces the file inside
# the `recipe_list_web` nginx container.
#
# Phase 1 form: <loc> uses the existing client path
# `/recipes/details/<id>` — no hreflang, no <xhtml:link rel="alternate">
# (those wait for chunks D–F once the client routes by locale).
#
# Run by /etc/cron.d/recipes-sitemap at 06:00 UTC daily, 30 minutes
# after the recipes-backfill cron at 05:30.
#
# Logging: appends to /var/log/recipes_sitemap.log with ISO timestamp.
# Exit non-zero on any step so cron MAILTO surfaces failures.

set -euo pipefail

API_HOST="${RECIPES_API_HOST:-http://172.25.0.41:4000}"
PUBLIC_HOST="${RECIPES_PUBLIC_HOST:-https://recipies.mahallem.ist}"
CONTAINER="${RECIPES_WEB_CONTAINER:-recipe_list_web}"
NGINX_PATH="${RECIPES_NGINX_PATH:-/usr/share/nginx/html/sitemap.xml}"
LOG_FILE="${RECIPES_SITEMAP_LOG:-/var/log/recipes_sitemap.log}"

stamp() { date -u +"%Y-%m-%dT%H:%M:%SZ"; }
log()   { printf '[%s] %s\n' "$(stamp)" "$*" | tee -a "$LOG_FILE"; }

trap 'log "ERROR exit=$?"' ERR

TMP_JSON="$(mktemp)"
TMP_XML="$(mktemp)"
trap 'rm -f "$TMP_JSON" "$TMP_XML"' EXIT

log "fetching $API_HOST/recipes/sitemap"
curl -fsS --max-time 20 "$API_HOST/recipes/sitemap" >"$TMP_JSON"

COUNT="$(jq 'length' "$TMP_JSON")"
if ! [[ "$COUNT" =~ ^[0-9]+$ ]] || [ "$COUNT" -lt 1 ]; then
  log "refusing to publish empty/invalid sitemap (count=$COUNT)"
  exit 2
fi

log "rendering sitemap with $COUNT recipe URLs"
{
  printf '%s\n' '<?xml version="1.0" encoding="UTF-8"?>'
  printf '%s\n' '<!-- generated by build_recipe_sitemap.sh — do not edit by hand -->'
  printf '%s\n' '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'

  printf '  <url>\n'
  printf '    <loc>%s/</loc>\n' "$PUBLIC_HOST"
  printf '    <changefreq>daily</changefreq>\n'
  printf '    <priority>1.0</priority>\n'
  printf '  </url>\n'
  printf '  <url>\n'
  printf '    <loc>%s/recipes</loc>\n' "$PUBLIC_HOST"
  printf '    <changefreq>daily</changefreq>\n'
  printf '    <priority>0.9</priority>\n'
  printf '  </url>\n'

  jq -r --arg base "$PUBLIC_HOST" '
    .[] |
    "  <url>\n" +
    "    <loc>\($base)/recipes/details/\(.id)</loc>\n" +
    "    <lastmod>\(.updatedAt)</lastmod>\n" +
    "    <changefreq>weekly</changefreq>\n" +
    "    <priority>0.8</priority>\n" +
    "  </url>"
  ' "$TMP_JSON"

  printf '%s\n' '</urlset>'
} >"$TMP_XML"

# Validate XML before publishing.
if command -v xmllint >/dev/null 2>&1; then
  xmllint --noout "$TMP_XML"
fi

log "publishing to $CONTAINER:$NGINX_PATH"
docker cp "$TMP_XML" "$CONTAINER:$NGINX_PATH"
docker exec "$CONTAINER" chown 0:0 "$NGINX_PATH" || true
docker exec "$CONTAINER" chmod 0644 "$NGINX_PATH" || true

log "done count=$COUNT bytes=$(wc -c <"$TMP_XML" | tr -d ' ')"
